spring:
  datasource:
   url: jdbc:mysql://localhost:3306/librick?useUnicode=yes&characterEncoding=UTF-8
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  context-path: /api/